### ISSUE TITLE
ActionResultCallback Error Blazor Server 

### ISSUE THREAD

**Issue by QadiymStewart** [canhorn/BabylonJS.Blazor.Game.Tutorial#5]
Trying to generate the Babylon bindings for Blazor  .NET 6 server-side but getting ActionResultCallback error.

Following this tutorial except for Blazor server-side not wasm.https://codyanhorn.tech/blog/babylonjs-and-blazor-getting-set-up

![image](https://user-images.githubusercontent.com/28968495/147420886-f874880f-7b56-42e3-8aae-e8dca5bc0ae3.png)

**Comment by canhorn** [comment]
Thanks for raising this issue!

To work around it you can use an older version of the ehz-generate tool: 
`dotnet tool install -g EventHorizon.Blazor.TypeScript.Interop.Tool --version 1.1.4`
This will generate a valid Blazor Server proxy based on the same ehz-generate command.

As for the issue, I forgot to update the Server Interop library with the ActionResultCallback feature. 
When I find some time in the next few days, I will update the base library to support ActionResultCallback's.
I will comment on this issue when I push up a new version.

**Comment by QadiymStewart** [comment]
@canhorn Thanks.

The work around I found in the mean time was to update all calls to  "ActionResultCallback"  using the old naming EventHorizon.Blazor.Server.Interop.Callbacks.ActionCallback

Now the only issue left is duplication warnings

![image](https://user-images.githubusercontent.com/28968495/147432772-b1271c28-0adc-455d-97ea-b7ecf346a958.png)

**Comment by canhorn** [comment]
@QadiymStewart I have a new release available for the ehz-generate tool, this should create a valid BabylonJS proxy for Balzor server.

For those current errors they look specific to the ASP.NET application project, I think it might be a problem with Visual Studio. Maybe a restart will fix it.

**Comment by QadiymStewart** [comment]
Thanks

**Comment by QadiymStewart** [comment]
@canhorn and for anyone else that might run into the issue.
Added below to my blazor .csproj file seems to resolve the other errors also deleted bin and obj folder and rebuild.

`<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>`
